# Generated by Django 5.1.2 on 2025-11-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('esalary', models.CharField(max_length=100)),
            ],
        ),
    ]
